<?php

namespace Collab\CollabBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HomeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Collab\CollabBundle\Controller\HomeController();
        return $instance;
    }
}
